import init, {InitInput, quicksort} from "./pkg/wasm_quicksort_example.js";

import {_Sortable} from "./autogenerated/bindings/index.js";

// NOTE: This is an issue with the roll-up plugin descibed in the build.sh
// TODO: Copy that over.
export type Sortable = _Sortable;

export type LoadOpts =  {
	wasm?: InitInput
};

let wasmInit: (() => InitInput) | undefined = undefined;
export const setWasmInit = (arg: () => InitInput) => {
  wasmInit = arg;
};

let initialized: Promise<void> | undefined = undefined;

export class Sorter {
	private constructor() {}

	public static initialize = async (options?: LoadOpts) => {
		if (initialized === undefined) {
			//@ts-ignore
			const loadModule = options?.wasm ?? wasmInit();
			initialized = init(loadModule).then(() => void 0);
		}

		await initialized;
		return new Sorter();
	}

	public sort = (sortable: Sortable): Sortable => {
		let s = JSON.stringify(sortable);
		s = quicksort(s);
		return JSON.parse(s) as Sortable;
	}
}
